os: linux
env:
    - SKELETON_VERSION="^3.4"
php: 7.1
dist: trusty
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files
group: stable
script:
    - composer require mukadi/wordpress-bundle dev-1.0.4-0
install:
    - composer create-project symfony/skeleton:${SKELETON_VERSION} app
    - cd app
    - composer config extra.symfony.allow-contrib true
language: php